/* Overwrite style */
var style = document.createElement('style');
style.innerHTML = `
    /* Hide elements */
	.nui_main_menu {display: none}
	.nui_left_box {display: none}
	.nui_grepo_score {display: none}
	.topleft_navigation_area {display: none}
	.ui_quickbar {display: none}
	.gods_area {display: none}
	.nui_right_box {display: none}
	.top_right_below {display: none}
	.top_right_left {display: none}
	.nui_units_box {display: none}
	.open_premium_button {display: none}

    /* Fix window size to fit screen */
    .ui-dialog {transform: scale(0.8, 0.8); top: -50px }
    .classic_window {transform: scale(0.8, 0.8); top: -50px !important}

    /* Fix top ui size */
    .nui_toolbar .left {height: 33px;}
    .nui_toolbar .right {height: 33px;}
    .town_name_area {transform: scale(1.1); transform-origin: top right; left: 42%}

    /* Move elements */
    #ui_box .toolbar_buttons {left: 145px}
    #ui_box .tb_activities {left: 235px}
    .ui_resources_bar {right: 10px;}

    /* Move gold */
    .premium_wrapper {height: 61px; left: 0px; top: -3px; transform: scaleX(-1);}   
    .gold_amount {transform: scaleX(-1);}
    .gods_spells_menu { display: none}
    
    /* Remove minimize and help */
    a.ui-dialog-titlebar-minimize {display: none}
    .help {display: none}
    .buttons_container .minimize {display: none !important}
    
    /* Move questions */
    #icons_container_left {top: 60px; left: 0px;}
    #questlog .questlog_icon:hover {margin-left: 0px;}
    /* Make close all window to fit the entire size -> user can easly click everywhere to close the window */
    .btn_close_all_windows {
        width: 100%;
        height: 100%;
        top: 0 !important;
        right: 0 !important;
        opacity: 0;
    }

    .btn_extend {
        display: none;
    }

    /* Zoom back map to make it more usable */
    #map {zoom: 0.7;}
    #compass {display: none}
    `;
document.getElementsByTagName('head')[0].appendChild(style);

/* Add left button */
function addLeftButton() {
	let position = '20px';
	let ui = document.getElementById('ui_box');
	let bttt = document.createElement('div');

	bttt.style.background =
		'url(https://gpit.innogamescdn.com/images/game/autogenerated/layout/construction_queue/construction_queue_2.74.png) no-repeat';
	bttt.style.backgroundPosition = '-373px -227px';
	bttt.style.width = '59px';
	bttt.style.height = '59px';
	bttt.style.position = 'absolute';
	bttt.style.left = position;
	bttt.style.bottom = position;
	bttt.style.zIndex = '10';
	ui.appendChild(bttt);

	let border = document.createElement('div');
	border.style.background =
		'url(//gpit-glps.innogamescdn.com/media/grepo/images/sprite-grepo-main.15b2a56c.png) no-repeat 0 0';
	border.style.backgroundPosition = '-1px -174px';
	border.style.width = '100px';
	border.style.height = '100px';
	border.style.position = 'absolute';
	border.style.left = position;
	border.style.bottom = position;
	border.style.zIndex = '9';
	border.style.scale = 0.8;
	border.style.translate = '-18% 22%';
	ui.appendChild(border);

	let current = 'city_overview';
	bttt.addEventListener('click', () => {
		if (current == 'city_overview') {
			document
				.getElementsByClassName('option island_view circle_button js-option')[0]
				.click();
			current = 'island_view';
			return;
		}
		if (current == 'island_view') {
			document
				.getElementsByClassName('option strategic_map circle_button js-option')[0]
				.click();
			current = 'strategic_map';
			return;
		}
		if (current == 'strategic_map') {
			document
				.getElementsByClassName('option city_overview circle_button js-option')[0]
				.click();
			current = 'city_overview';
			return;
		}
	});
}

/* Add right button */
function addRightButton() {
	let position = '20px';
	let ui = document.getElementById('ui_box');
	let bttt = document.createElement('div');

	bttt.style.background =
		'url(https://gpit.innogamescdn.com/images/game/autogenerated/layout/construction_queue/construction_queue_2.74.png) no-repeat';
	bttt.style.backgroundPosition = '-373px -227px';
	bttt.style.width = '59px';
	bttt.style.height = '59px';
	bttt.style.position = 'absolute';
	bttt.style.right = position;
	bttt.style.bottom = position;
	bttt.style.zIndex = '10';
	ui.appendChild(bttt);

	let border = document.createElement('div');
	border.style.background =
		'url(//gpit-glps.innogamescdn.com/media/grepo/images/sprite-grepo-main.15b2a56c.png) no-repeat 0 0';
	border.style.backgroundPosition = '-1px -174px';
	border.style.width = '100px';
	border.style.height = '100px';
	border.style.position = 'absolute';
	border.style.right = position;
	border.style.bottom = position;
	border.style.zIndex = '9';
	border.style.scale = 0.8;
	border.style.translate = '23% 22%';
	ui.appendChild(border);

	let current = 'city_overview';
	bttt.addEventListener('click', () => {
		if (current == 'city_overview') {
			document
				.getElementsByClassName('option island_view circle_button js-option')[0]
				.click();
			current = 'island_view';
			return;
		}
		if (current == 'island_view') {
			document
				.getElementsByClassName('option strategic_map circle_button js-option')[0]
				.click();
			current = 'strategic_map';
			return;
		}
		if (current == 'strategic_map') {
			document
				.getElementsByClassName('option city_overview circle_button js-option')[0]
				.click();
			current = 'city_overview';
			return;
		}
	});
}

try {
	addLeftButton();
	addRightButton();

	let questlog = document.getElementById('questlog');
	questlog.getElementsByClassName('caption js-caption')[0].remove();
} catch (error) {
	alert(error);
}

/* Fix context menu to work with fingher click */
setTimeout(() => {
	const map = document.getElementById('wmap');

	var lastMove = null;
	var present = {
		x: null,
		y: null,
	};
	map.addEventListener('touchstart', function (event) {
		lastMove = event;
		const menu = document.getElementById('context_menu');
		if (!menu) present = { x: null, y: null };
		else {
			present = {
				x: menu.style.left,
				y: menu.style.top,
			};
		}
	});
	map.addEventListener('touchend', () => {
		setTimeout(() => {
			const menu = document.getElementById('context_menu');
			if (!menu) return;
			menu.style.left = `${lastMove.touches[0].pageX - 20}px`;
			menu.style.top = `${lastMove.touches[0].pageY - 20}px`;
			menu.style.scale = 0.8;
			menu.style.zIndex = 5001;
			present = {
				x: menu.style.left,
				y: menu.style.top,
			};
		}, 100);
	});
	var observer = new MutationObserver(function (mutations) {
		let menu = document.getElementById('context_menu');
		if (menu == undefined) return;
		if (present.x == menu.style.left && present.y == menu.style.top) return;
		if (document.contains(menu)) {
			menu.style.zIndex = 0;
		}
	});

	observer.observe(document, {
		attributes: false,
		childList: true,
		characterData: false,
		subtree: true,
	});
	/* Hide notification area */
	document.getElementById('notification_area').style.display = 'none';
	/* Add functions to buttons */
	let goldArea = document.getElementsByClassName('premium_area premium_wrapper')[0];
	goldArea.addEventListener('click', () => {
		PremiumWindowFactory.openBuyGoldWindow();
	});
}, 1000);

/* 
Minimap.zoomIn();
document.getElementsByClassName("option strategic_map circle_button js-option")[0].click()
document.getElementsByClassName("option island_view circle_button js-option")[0].click()
document.getElementsByClassName("option city_overview circle_button js-option")[0].click()
*/
